name: Output information
on:
    issues:
        types: [opened, edited, closed, reopened]
jobs:
    respond-to-issue:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Respond to issue
            run: echo "Issue event occurred!"
    output-info:
      runs-on: ubuntu-latest
      steps:
        - name: Output event details
          run: echo "Event details: ${{ toJson(github.event) }}"
